#!/usr/bin/env bash
set -e

if [ $# -eq 0 ]
  then
    tag="latest"
  else
    tag=$1
fi

echo "Using tag $tag"

dingo -src=./internal/config/di -dest=./generated

docker build -f ./build/address-validator/Dockerfile . -t navexplorer/address-validator:$tag
docker push navexplorer/address-validator:$tag
